# create transparent animated gif of sequence layer
# output: ../sequences/gif/gen_animated_[layer #].gif
# TODO: refactor

ffmpeg -framerate 10 -i ../sequences/0/gen_%08d.png -i ../sequences/0/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_0.gif
ffmpeg -framerate 10 -i ../sequences/1/gen_%08d.png -i ../sequences/1/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_1.gif
ffmpeg -framerate 10 -i ../sequences/2/gen_%08d.png -i ../sequences/2/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_2.gif
ffmpeg -framerate 10 -i ../sequences/3/gen_%08d.png -i ../sequences/3/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_3.gif
ffmpeg -framerate 10 -i ../sequences/4/gen_%08d.png -i ../sequences/4/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_4.gif
ffmpeg -framerate 10 -i ../sequences/5/gen_%08d.png -i ../sequences/5/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_5.gif
ffmpeg -framerate 10 -i ../sequences/6/gen_%08d.png -i ../sequences/6/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_6.gif
ffmpeg -framerate 10 -i ../sequences/7/gen_%08d.png -i ../sequences/7/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_7.gif
ffmpeg -framerate 10 -i ../sequences/8/gen_%08d.png -i ../sequences/8/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_8.gif
ffmpeg -framerate 10 -i ../sequences/9/gen_%08d.png -i ../sequences/9/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_9.gif
ffmpeg -framerate 10 -i ../sequences/10/gen_%08d.png -i ../sequences/10/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_10.gif
ffmpeg -framerate 10 -i ../sequences/11/gen_%08d.png -i ../sequences/11/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_11.gif
ffmpeg -framerate 10 -i ../sequences/12/gen_%08d.png -i ../sequences/12/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_12.gif
ffmpeg -framerate 10 -i ../sequences/13/gen_%08d.png -i ../sequences/13/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_13.gif
ffmpeg -framerate 10 -i ../sequences/14/gen_%08d.png -i ../sequences/14/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_14.gif
ffmpeg -framerate 10 -i ../sequences/15/gen_%08d.png -i ../sequences/15/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_15.gif
ffmpeg -framerate 10 -i ../sequences/16/gen_%08d.png -i ../sequences/16/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_16.gif
ffmpeg -framerate 10 -i ../sequences/17/gen_%08d.png -i ../sequences/17/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_17.gif
ffmpeg -framerate 10 -i ../sequences/18/gen_%08d.png -i ../sequences/18/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_18.gif
ffmpeg -framerate 10 -i ../sequences/19/gen_%08d.png -i ../sequences/19/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_19.gif
ffmpeg -framerate 10 -i ../sequences/20/gen_%08d.png -i ../sequences/20/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_20.gif
ffmpeg -framerate 10 -i ../sequences/21/gen_%08d.png -i ../sequences/21/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_21.gif
ffmpeg -framerate 10 -i ../sequences/22/gen_%08d.png -i ../sequences/22/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_22.gif
ffmpeg -framerate 10 -i ../sequences/23/gen_%08d.png -i ../sequences/23/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_23.gif
ffmpeg -framerate 10 -i ../sequences/24/gen_%08d.png -i ../sequences/24/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_24.gif
ffmpeg -framerate 10 -i ../sequences/25/gen_%08d.png -i ../sequences/25/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_25.gif
ffmpeg -framerate 10 -i ../sequences/26/gen_%08d.png -i ../sequences/26/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_26.gif
ffmpeg -framerate 10 -i ../sequences/27/gen_%08d.png -i ../sequences/27/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_27.gif
ffmpeg -framerate 10 -i ../sequences/28/gen_%08d.png -i ../sequences/28/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_28.gif
ffmpeg -framerate 10 -i ../sequences/29/gen_%08d.png -i ../sequences/29/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_29.gif
ffmpeg -framerate 10 -i ../sequences/30/gen_%08d.png -i ../sequences/30/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_30.gif
ffmpeg -framerate 10 -i ../sequences/31/gen_%08d.png -i ../sequences/31/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_31.gif
ffmpeg -framerate 10 -i ../sequences/32/gen_%08d.png -i ../sequences/32/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_32.gif
ffmpeg -framerate 10 -i ../sequences/33/gen_%08d.png -i ../sequences/33/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_33.gif
ffmpeg -framerate 10 -i ../sequences/34/gen_%08d.png -i ../sequences/34/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_34.gif
ffmpeg -framerate 10 -i ../sequences/35/gen_%08d.png -i ../sequences/35/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_35.gif
ffmpeg -framerate 10 -i ../sequences/36/gen_%08d.png -i ../sequences/36/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_36.gif
ffmpeg -framerate 10 -i ../sequences/37/gen_%08d.png -i ../sequences/37/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_37.gif
ffmpeg -framerate 10 -i ../sequences/38/gen_%08d.png -i ../sequences/38/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_38.gif
ffmpeg -framerate 10 -i ../sequences/39/gen_%08d.png -i ../sequences/39/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_39.gif
ffmpeg -framerate 10 -i ../sequences/40/gen_%08d.png -i ../sequences/40/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_40.gif
ffmpeg -framerate 10 -i ../sequences/41/gen_%08d.png -i ../sequences/41/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_41.gif
ffmpeg -framerate 10 -i ../sequences/42/gen_%08d.png -i ../sequences/42/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_42.gif
ffmpeg -framerate 10 -i ../sequences/43/gen_%08d.png -i ../sequences/43/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_43.gif
ffmpeg -framerate 10 -i ../sequences/44/gen_%08d.png -i ../sequences/44/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_44.gif
ffmpeg -framerate 10 -i ../sequences/45/gen_%08d.png -i ../sequences/45/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_45.gif
ffmpeg -framerate 10 -i ../sequences/46/gen_%08d.png -i ../sequences/46/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_46.gif
ffmpeg -framerate 10 -i ../sequences/47/gen_%08d.png -i ../sequences/47/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_47.gif
ffmpeg -framerate 10 -i ../sequences/48/gen_%08d.png -i ../sequences/48/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_48.gif
ffmpeg -framerate 10 -i ../sequences/49/gen_%08d.png -i ../sequences/49/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_49.gif
ffmpeg -framerate 10 -i ../sequences/50/gen_%08d.png -i ../sequences/50/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_50.gif
ffmpeg -framerate 10 -i ../sequences/51/gen_%08d.png -i ../sequences/51/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_51.gif
ffmpeg -framerate 10 -i ../sequences/52/gen_%08d.png -i ../sequences/52/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_52.gif
ffmpeg -framerate 10 -i ../sequences/53/gen_%08d.png -i ../sequences/53/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_53.gif
ffmpeg -framerate 10 -i ../sequences/54/gen_%08d.png -i ../sequences/54/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_54.gif
ffmpeg -framerate 10 -i ../sequences/55/gen_%08d.png -i ../sequences/55/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_55.gif
ffmpeg -framerate 10 -i ../sequences/56/gen_%08d.png -i ../sequences/56/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_56.gif
ffmpeg -framerate 10 -i ../sequences/57/gen_%08d.png -i ../sequences/57/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_57.gif
ffmpeg -framerate 10 -i ../sequences/58/gen_%08d.png -i ../sequences/58/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_58.gif
ffmpeg -framerate 10 -i ../sequences/59/gen_%08d.png -i ../sequences/59/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_59.gif
ffmpeg -framerate 10 -i ../sequences/60/gen_%08d.png -i ../sequences/60/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_60.gif
ffmpeg -framerate 10 -i ../sequences/61/gen_%08d.png -i ../sequences/61/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_61.gif
ffmpeg -framerate 10 -i ../sequences/62/gen_%08d.png -i ../sequences/62/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_62.gif
ffmpeg -framerate 10 -i ../sequences/63/gen_%08d.png -i ../sequences/63/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_63.gif
ffmpeg -framerate 10 -i ../sequences/64/gen_%08d.png -i ../sequences/64/palette.png -lavfi paletteuse=alpha_threshold=128 ../sequences/gif/gen_animated_64.gif